### ISSUE TITLE
application configuration

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/mpr-research-data#1]
Some things about this application should be configurable, especially for deployment to OpenShift.  For example…

* DB credentials
* GCP credentials
* number of months to look back for data

These things will be added to the project in OpenShift as a secret or configmap.  That way, they do not need to be committed to this repo in order to make them available on OpenShift.  This is a very good way to prevent credentials from becoming public.

Some configuration items should have default values, like the number of months.  Credentials definitely should not have defaults and an error should be given if the credentials aren't available.

**Comment by takposha** [comment]
Config has been made. User outlines GCP project and bucket details, number of months. Credentials are added as JSON files which are used to authenticate.
