### ISSUE TITLE
config processing

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/mpr-research-data#11]
Several thoughts about config processing.  If you think these should be split into multiple issues, feel free to create new issues that reference this one.

1. Create a `config()` function.  Rather than putting the code at the highest level without a function to contain it, move it into a new function.  It should be one that returns a dictionary of  configuration keys or a configuration object.  If it returns a dictionary, you may use an enumeration to define the keys.  If it returns an object, make sure all the possible properties are declared.
2. For each configuration key, ensure that those without default values are not blank/undefined.
3. Check that the type of each configuration value is correct.  We don't want the config to assign a string to a config item that should be a number.  The same with assigning some non-JSON value to the GCP credentials key.
4. Move the `os.getenv()` calls for the DB and GCP credentials into this new `config()` function, too.
5. The main program (see #10) should call this new `config()` function.  It could either store the results in a global variable or (better) define a class for the whole application and let the configuration be a property in the object defined by that class.

**Comment by takposha** [comment]
Do we want the program to stop entirely if env variables are incorrect, or do we try to default to known values? 
This would be a case-by-case thing as I think things like username and password come in pairs, for example, defaulting one while other changes won't be that helpful. 

Or interpreting that if someone has changed from defaults, you would expect them to explicitly not run defaults and so stop execution if it doesn't work.
