### ISSUE TITLE
documentation (`README.md`, etc.)

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/mpr-research-data#2]
The project has rough documentation in the `steps.md` file.  Make new documentation in the file `README.md`.  It can be a cleaned-up form of the current docs and there's probably more to be added.  If the documentation seems to be too long for a single file, it can be broken into other files, with links from the README.

**Comment by takposha** [comment]
README.md has been added with steps outlined. config.env also outlines key variables used and to be adjusted.
