### ISSUE TITLE
use logging library

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/mpr-research-data#7]
_Originally posted by @lsloan in https://github.com/tl-its-umich-edu/mpr-research-data/pull/3#discussion_r868451198_
> That sounds like a good solution.  I think it effectively disables buffering.
>
> We may want to switch to some sort of standard logging, but we can leave that to another PR.  I'll make an issue for that, too.

Replace printing of various status and error messages with calls to the Python logging library.  That will put messages into a standard format, including timestamp, message type (info, error, debug, etc.), and the line in the code where the logging occurred.

**Comment by takposha** [comment]
A logging system has been implemented. ISO 8601 timestamp - Error level - Filename, File line - Message.
